version: "3.8"

services:
  
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
      
  app:
    container_name: app
    build: .
    image: poseidon
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8085:8080"
    depends_on:
      - "db"
    
    